---
language: java

install:
  - ls -lad /usr/local/maven
  - wget -O - http://apache.mirrors.pair.com/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz | sudo tar xvz -C /usr/local
  - sudo rm /usr/local/maven
  - sudo ln -s /usr/local/apache-maven-3.3.9 /usr/local/maven
  - ls -lad /usr/local/maven

script: mvn -q install -P examples
jdk:
- openjdk7
matrix:
  include:
  - jdk: oraclejdk7
    script: mvn -q install
    after_success: mvn -q deploy --settings .travis-settings.xml -Dno.gem.deploy=true -DskipTests=true -Dmaven.javadoc.skip=true
  - jdk: oraclejdk8
    script: mvn -q install -P java8
    after_success: mvn -q deploy -P java8 -pl java8 --settings .travis-settings.xml -DskipTests=true -Dmaven.javadoc.skip=true

sudo: true

branches:
  only:
  - master
notifications:
  email:
  - cukes-devs@googlegroups.com
